# Workflow for deploying to Hugging Face hub
name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]  # Enable automatic deployment on push to main
  workflow_dispatch:    # Keep manual trigger option

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Create clean branch
        run: |
          # Remove ChromaDB files
          rm -rf runtime_chroma/
          rm -rf chroma_db/
          # Create clean branch without binary files
          git checkout --orphan temp-clean
          git add -A
          git commit -m "Clean history deployment"
      - name: Write environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          git add .env
          git commit --amend --no-edit
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://afewell:$HF_TOKEN@huggingface.co/spaces/afewell/hh-agent-tails
          git push -f space temp-clean:main 